{% set name = "pgplot" %}
{% set majmin = "5.2" %}
{% set patch = "2" %}
{% set sha256 = "a5799ff719a510d84d26df4ae7409ae61fe66477e3f1e8820422a9a4727a5be4" %}

package:
  name: {{ name|lower }}
  version: {{ majmin }}.{{ patch }}

source:
  fn: {{ name }}{{ majmin }}.tar.gz
  url: http://fossies.org/unix/misc/old/{{ name }}{{ majmin }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - drivers.patch
    - gfortran.patch
    - png-setjmp.patch
    - prefix.patch
    - late-binding-drivers.patch
    - osx.patch  # [osx]

build:
  number: 2
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - gcc  # [osx]
    - libgfortran  # [linux]
    - libpng >=1.6.28,<1.7
    - toolchain
    - xorg-libx11
    - zlib 1.2.*
  run:
    - libgfortran
    - libpng >=1.6.28,<1.7
    - xorg-libx11
    - zlib 1.2.*

test:
  commands:
    - test -x $PREFIX/bin/pgxwin_server
    - test -f $PREFIX/lib/libpgplot.a  # [unix]
    - test -f $PREFIX/lib/libpgplot.so  # [linux]
    - test -f $PREFIX/lib/libpgplot.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.astro.caltech.edu/~tjp/pgplot/
  license: non-commercial use only
  summary: 'A FORTRAN plotting library'

extra:
  recipe-maintainers:
    - pkgw
