appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F3SEcRzhvkoUNgv1z71DeTcukkFtYZChupDUBiKal3++Ftf5m3DrwPOqY06mk3FBye1T3HpoI9nWWMB4KFZeXoWiPoogbCIbtD7Zxdx2tmnpvllV9KulJ3i4ZDx3hiFx0Cc9Vf4vPxzLcTwNC+nANPd4E04ceTCWUWfp2XoOMJzqL5fl+AtGMpj8n0OyOPNR+cCAQSjxUaEHhlYENCbUxovKdSxVimzUCQHjvROW/2+Mzx7vmCGRN4wlBoZfoWYnRpvlincPnL3xcA57kHYnPrNL+Xr3R3FDNxEcKUEmlszBc2tcfFDdbGO57OTXalRVCclc1bVtCJgtx8S3YcV5PCh1waLZWDXjrX3ZQ5ZmyVvE8FrUUWj2w+qptlqpS9rE1LeUfDZHqnMX7ryib1NC4ha0L2ufLonaTmysPrg/fgJGSstjuDy/10Ee6QymJ9xo4wgqykkIT+jRsg1QGB27iv3vrw/9NPMCei8INfB0m4QOk00QDGY+awPeRDa0uyN9nXHuKRBDkrCcf3JkGTdjMHM974070L27LFLVnwfnFivypNHv6jaOaE75jXOQLpi3f4/g5IzIrh96vDE5eyxxmqbSLSwfuiiYBfTlnH0Xihuo657/1w0tO4/lLaoSBIKIQ86yhLrzy5ONsAZgMPdi9dGl8FOBwaMYYeAjf5Ks3Lc=}
conda_forge_output_validation: true
