travis:
  secure:
    BINSTAR_TOKEN: JReiB/r/5NyvTeytrt9Vm0OXRIxP7ibhTy8dw5BFj4/EuSM7ZIJKAp/Ulx2B5JDPLBWYvuWTMxRkZlic1ucqnbXd/VwxNe9vJFJHbep5DbQd0BdLaSZNUd0eQiIUrZlLEZVcjJaC6RT1K8xXqt+5Af2mR+7ufJNTMku9D8FufpR++t7bdIfuuEXx89nUP8f+gPuzP8SzEatk5dJn2gYfClNqYKtFSRoFi8rMtvgaKNoCtjVj8KMuUe5vlh2un1qFhY03fBXwDsxG8XK5dWblB3GkzHKK7Qbpsucqca+DP+WhAzJooDrmca6p3ASbucOuCn22IbQ428qofmyl9js/xGQjz6DWLDQIfm9TfkQHdpeQEsxMnS++sXa7rmLu3Lk2ldjM86YrIn7QdD4IcdRlFgHr89ulK/nLO5wPJmAxSklKLw1ZitIs4fdfKa9GMo8vwYgxZfwYSXI8kf6+NknnNNp9pZMvxs/iEuj6uHacVVy5nS8zsSUzxbDWbE1hSx8LC9Ss1IIsLizcWoLAucuITafEbpaax+BGi9DoIurIgKtvjpI6SrD4eDRqiA3mRaGft4sIdZ8OVylMggcCuIF8LjVHGMkD3EaBuUxayGuCMN+C58rjKlXztvO8mSf44MPQHxYVlHee5CvDhT/Se8WPgrdm6dahFv1aUrgP7Y3BSHw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
